# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Install Compose
      uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command
  
    - run: docker-compose --version

    - name: create service
      run: |
        curl -i -s -X POST http://localhost:8001/services --data name=example_service --data url='http://httpbin.org'

    # start kong dockers
    - run: docker-compose up -d
    - name: test kong-cp starts up
      run: |
        curl -X GET http://localhost:8001/services

    # run tests

    # tear down
    - name: tear down
      if: always()
      run: docker-compose down 
