# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Install Compose
      uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command
  
    - run: docker-compose --version

    # start kong dockers
    - run: docker-compose up -d
    - name: check kong-cp started
      run: |
        cmd="curl -X GET http://localhost:8001/services"; for i in {1..31}; do eval $cmd; if [ $? -eq 0 ]; then break; fi; if [ $i -ge 30 ]; then echo "service not started in $ seconds"; exit(1); fi; sleep 1; done

    - name: test kong-cp starts up
      if: always()
      run: |
        curl -X GET http://localhost:8001/services
  
    - name: create service
      if: always()
      run: |
        curl -i -s -X POST http://localhost:8001/services --data name=example_service --data url='http://httpbin.org'

    - name: check kong-cp log
      if: always()
      run: |
        docker logs kong-cp
    
    - name: check created kong-cp services
      if: always()
      run: |
        curl -X GET http://localhost:8001/services

    # run tests

    # tear down
    - name: tear down
      if: always()
      run: docker-compose down 
